### ISSUE TITLE
Async Support

### ISSUE THREAD

**Issue by TheOnlyWayUp** [0x44F/discord-token-gen#1]
From an initial read of the codebase, it doesn't look like the program supports async.

Asynchronous Code performs better than threading, and is simply better, especially when trying to blast out requests ;)

**Comment by TheOnlyWayUp** [comment]
While we're at it, could you explain [gen.hpp#L12](https://github.com/0x44F/discord-token-gen/blob/main/src/gen.hpp#L12)'s comment on AI-Based Credential Generation?

Do you mean it uses the random emails provided by tempmail?

**Comment by 0x44F** [comment]
Uses AI to make a strong random password.

**Comment by 0x44F** [comment]
We also cannot use asynchronous requests because this method only allows creation of one account at a time
